### ISSUE TITLE
Zwischenfeedback

### ISSUE THREAD

**Issue by michael-spengler** [0x7477/DonationSimulator#1]
Readme einführen. Link auf Deine bestehende Doku Datei hinzufügen. 

Klare Labels (Percent vs. Percentage - add (conversion rate) in brackets)

Globale Parameter
Charity Parameter
x y Achse Beschriftung?

Reference to .js file vs. .ts file?
https://github.com/0x7477/DonationSimulator/blob/master/donation_simulator/src/lib/ts/charity.ts#L2

**Comment by michael-spengler** [comment]
https://github.com/VoFarm/bollinger_bands/blob/main/.vscode/settings.json

**Comment by michael-spengler** [comment]
>= 1,4

**Comment by 0x7477** [comment]
Done :)

**Comment by michael-spengler** [comment]
(Zusätzliche) Screenshots der web app innerhalb der readme oder ein link auf die "deployte" web app an sich wäre m.E. perfekt um anhand der readme noch schneller zu checken wie genau die web app aussieht und benutzt werden kann.
